site_name: oalfonso
site_url: https://oalfonso.com/
nav:
    - Home: index.md
    - Posts: posts.md
    - About: about.md
theme:
    name: material
    features:
        - content.code.annotate
    # name: mkdocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
